# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.15
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: satishchoudhari13579@gmail.com
author_name: satishccy
contract_name: votte
deployment_language: python
preset_name: starter
project_name: votte

